### ISSUE TITLE
Specify (guess?) all relevant hardware

### ISSUE THREAD

**Issue by fulldecent** [mattzzw/kindle-gphotos#1]
Thank you for sharing. The project may benefit to show all possible hardware that would be compatible. Oasis? Which models? etc.

---

FYI, I'm thinking to extend (subtract) from this project to just load a PNG file from a web server hourly. Then I could use it as a status board for my office door. People pay a lot of money to buy specialized hardware and software to do this. Could you say how many updates your are getting on a single battery charge when you use this?

**Comment by mattzzw** [comment]
The code is suitable for a kindle paperwhite (PW2 and PW3). There are some device specific items in the code (suspend to ram, display rotation, backlight, ...). But you can probably take the code and adapt it for any jailbroken kindle.

Regarding run time: I'm getting about 3 months run time, updating every 24h, so about 90 updates on a kindle paperwhite.
In my case the number of updates are not the limiting factor but the current that is used in suspend to ram mode.
Updating the display every minute will result in about 8 days runtime. Here the current in powered up mode is the limiting factor. Running the numbers, the 1600mAh battery in a paperwhite, using it for 5 secs @ 100mA will give you 11520 updates. But suspend to ram will also consume a little current. 
So my guess is that you will end up with a couple of weeks of run time with hourly updates.

**Comment by fulldecent** [comment]
Thank you, this is all super helpful! Added PR #2.

I'm looking now to get the PW2 or PW3 for this project. It seems like getting the correct hardware/firmware might be the hardest part.
